INT_MIN = -2 ** 31
INT_MAX = 2 ** 31 - 1

FLOAT_MIN = -3.402823e+38
FLOAT_MAX = 3.402823e+38

# property_name: (default_value, minimum, maximum)
values = {
    'mol_active': False,
    'mol_bakeuv': False,
    'mol_collision_damp': (0.005, 0.0, 1.0),
    'mol_collision_group': (1, 1, INT_MAX),
    'mol_density': (1000.0, 0.001, FLOAT_MAX),
    'mol_density_active': False,
    'mol_friction': (0.005, 0.0, 1.0),
    'mol_link_broken': (0.5, 0.0, FLOAT_MAX),
    'mol_link_broken_mode': 'CONSTANT',
    'mol_link_broken_samevalue': True,
    'mol_link_brokenrand': (0.0, 0.0, 1.0),
    'mol_link_brokentex': '',
    'mol_link_brokentex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_damp': (1.0, 0.0, 1.0),
    'mol_link_damp_mode': 'CONSTANT',
    'mol_link_damp_samevalue': True,
    'mol_link_damprand': (0.0, 0.0, 1.0),
    'mol_link_damptex': '',
    'mol_link_damptex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_ebroken': (0.5, 0.0, FLOAT_MAX),
    'mol_link_ebrokenrand': (0.0, 0.0, 1.0),
    'mol_link_ebrokentex': '',
    'mol_link_ebrokentex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_edamp': (1.0, 0.0, 1.0),
    'mol_link_edamprand': (0.0, 0.0, 1.0),
    'mol_link_edamptex': '',
    'mol_link_edamptex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_estiff': (1.0, 0.0, 1.0),
    'mol_link_estiffrand': (0.0, 0.0, 1.0),
    'mol_link_estifftex': '',
    'mol_link_estifftex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_friction': (0.005, 0.0, 1.0),
    'mol_link_friction_mode': 'CONSTANT',
    'mol_link_frictionrand': (0.0, 0.0, 1.0),
    'mol_link_frictiontex': '',
    'mol_link_frictiontex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_group': (1, 1, INT_MAX),
    'mol_link_length': (1.0, 0.0, FLOAT_MAX),
    'mol_link_max': (16, 0, INT_MAX),
    'mol_link_rellength': True,
    'mol_link_stiff': (1.0, 0.0, 1.0),
    'mol_link_stiff_mode': 'CONSTANT',
    'mol_link_stiff_samevalue': True,
    'mol_link_stiffrand': (0.0, 0.0, 1.0),
    'mol_link_stifftex': '',
    'mol_link_stifftex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_link_tension': (1.0, 0.0, FLOAT_MAX),
    'mol_link_tension_mode': 'CONSTANT',
    'mol_link_tensionrand': (0.0, 0.0, 1.0),
    'mol_link_tensiontex': '',
    'mol_link_tensiontex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_links_active': False,
    'mol_matter': -1,
    'mol_other_link_active': False,
    'mol_othercollision_active': False,
    'mol_refresh': True,
    'mol_relink_broken': (0.5, 0.0, FLOAT_MAX),
    'mol_relink_broken_mode': 'CONSTANT',
    'mol_relink_broken_samevalue': True,
    'mol_relink_brokenrand': (0.0, 0.0, 1.0),
    'mol_relink_brokentex': '',
    'mol_relink_brokentex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_chance': (0.0, 0.0, 100.0),
    'mol_relink_chance_mode': 'CONSTANT',
    'mol_relink_chancerand': (0.0, 0.0, 1.0),
    'mol_relink_chancetex': '',
    'mol_relink_chancetex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_damp': (1.0, 0.0, 1.0),
    'mol_relink_damp_mode': 'CONSTANT',
    'mol_relink_damp_samevalue': True,
    'mol_relink_damprand': (0.0, 0.0, 1.0),
    'mol_relink_damptex': '',
    'mol_relink_damptex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_ebroken': (0.5, 0.0, FLOAT_MAX),
    'mol_relink_ebrokenrand': (0.0, 0.0, 1.0),
    'mol_relink_ebrokentex': '',
    'mol_relink_ebrokentex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_edamp': (1.0, 0.0, 1.0),
    'mol_relink_edamprand': (0.0, 0.0, 1.0),
    'mol_relink_edamptex': '',
    'mol_relink_edamptex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_estiff': (1.0, 0.0, 1.0),
    'mol_relink_estiffrand': (0.0, 0.0, 1.0),
    'mol_relink_estifftex': '',
    'mol_relink_estifftex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_friction': (0.005, 0.0, 1.0),
    'mol_relink_friction_mode': 'CONSTANT',
    'mol_relink_frictionrand': (0.0, 0.0, 1.0),
    'mol_relink_frictiontex': '',
    'mol_relink_frictiontex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_group': (1, 1, INT_MAX),
    'mol_relink_max': (16, 0, INT_MAX),
    'mol_relink_stiff': (1.0, 0.0, 1.0),
    'mol_relink_stiff_mode': 'CONSTANT',
    'mol_relink_stiff_samevalue': True,
    'mol_relink_stiffrand': (0.0, 0.0, 1.0),
    'mol_relink_stifftex': '',
    'mol_relink_stifftex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_relink_tension': (1.0, 0.0, FLOAT_MAX),
    'mol_relink_tension_mode': 'CONSTANT',
    'mol_relink_tensionrand': (0.0, 0.0, 1.0),
    'mol_relink_tensiontex': '',
    'mol_relink_tensiontex_coeff': (1.0, FLOAT_MIN, FLOAT_MAX),
    'mol_selfcollision_active': False,
    'mol_var1': (1000, 1, INT_MAX),
    'mol_var2': (4, 1, INT_MAX),
    'mol_var3': (1000, 1, INT_MAX)
}
